### ISSUE TITLE
VS Code Intellisense not working

### ISSUE THREAD

**Issue by mozark24** [hackwaly/vscode-ocaml#112]
Following the "Setup guide" (if one can call it that) as closely as possible and I cannot get the intellisense to correctly work on VS Code.  I get "Loading" hovering the mouse over words.  Really think the install procedures could use some cleaning up...  Any suggestions?

**Comment by hackwaly** [comment]
Try set `ocaml.merlinPath` to a full path. I guess your merlin not exists in your `$PATH`.

**Comment by mozark24** [comment]
I double checked my path (both in Cygwin, and in VSCode)
At the top of my $PATH:   
`/home/User/.opam/4.05.0+mingw32c/bin` 
In VSCode settings overwriting default:  
`"ocaml.merlinPath": "G:/OCaml/home/User/.opam/4.05.0+mingw32c/bin/ocamlmerlin"`  

I also tried substituting `\\` for `/` to no avail.  Can you post yours as example?

**Comment by hackwaly** [comment]
Your config is correct.

My OS is macOS. I'll check it in windows VM later. If you'd like to get it work in a hurry, and you know typescript. You can debug ocaml extension to figure out what's wrong.

**Comment by mozark24** [comment]
Copy.  Thank you for your assistance and assurance.  I do not know typescript and I'm about ready to head to bed for the night.  Will check-in later.

**Comment by hackwaly** [comment]
This is likely a bug on Windows OS of merlin 3.0.2.0, I've tested ocaml `4.05.0+mingw64c` + merlin `3.0.2.0`. It doesn't work, too. If you execute `ocamlmerlin` in cygwin's terminal, it will stuck the terminal.

I've tested ocaml `4.04.2+mingw64c` + merlin `2.5.5`. It works properly. For now, you can switch to 4.04.2 on Windows OS to use vscode-ocaml.

**Comment by Simn** [comment]
I'm also having some issues after switching to OCaml 4.05.0+mingw64c. This message appears in the dev console a lot:

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 This socket is closed: Error: This socket is closed
	at Socket._writeGeneric (net.js:692:19)
	at Socket._write (net.js:743:8)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Socket.Writable.write (_stream_writable.js:241:11)
	at Socket.write (net.js:670:40)
	at Interface._writeToOutput (readline.js:250:17)
	at Interface.prompt (readline.js:215:10)
	at Interface.question (readline.js:223:12)
	at Promise (C:\Users\simn\.vscode\extensions\hackwaly.ocaml-0.6.41\out\src\merlin.js:59:26)
```

Everything was working great with OCaml 4.02.3.
